import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    borderRadius: 6,
    backgroundColor: "#17232c",
    marginTop: 14,
  },
  headerContainer: {
    flexDirection: "row",
    paddingVertical: 10,
    justifyContent: "space-between",
    alignItems: "center",
  },
  headerTitleContainer: { flexDirection: "row", alignItems: "center", gap: 5 },
  headerTitle: { color: "#ffffff" },
  datePickerButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  buttonIcon: {
    width: 14,
    height: 14,
  },
  datePickerText: { color: "#ffffff" },
  cardsContainer: {
    flexDirection: "column",
    gap: 12,
    maxHeight: 800,
  },
  headerIcon: {
    width: 18,
    height: 18,
  },
  fixtureContainer: {
    borderLeftWidth: 2,
    borderLeftColor: "#30c3a2",
    flexDirection: "column",
    alignItems: "center",
    backgroundColor: "#2b383e",
    padding: 10,
    borderRadius: 6,
  },
  dateContainer: {
    width: "100%",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    color: "#d4d4d4",
    marginBottom: 6,
  },
  fixtureTime: { fontSize: 11, color: "#ffffff" },
  fixtureDate: { fontSize: 11, color: "#ffffff" },
  infoContainer: {
    flexDirection: "column",
    alignItems: "center",
    gap: 5,
    borderRadius: 6,
    backgroundColor: "#384348",
    padding: 5,
  },
  leagueContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 5,
  },
  leagueLogo: {
    width: 16,
    height: 16,
  },
  leagueName: {
    fontSize: 12,
    color: "#ffffff",
  },
  teamsContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    borderTopWidth: 1,
    borderTopColor: "#2b383e",
    paddingVertical: 10,
  },
  vsText: {
    flex: 0.2,
    textAlign: "center",
    fontWeight: 500,
    color: "#30c3a2",
  },
  teamContainer: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 5,
  },
  teamName: {
    flex: 1,
    fontWeight: "500",
    color: "#fff",
    fontSize: 16,
  },
  teamLogoContainer: {
    backgroundColor: "white",
    borderRadius: 50,
    padding: 5,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    width: 40,
    height: 40,
  },
  teamLogo: {
    width: 24,
    height: 24,
  },
});
